---
  - name: install quagga
    yum:
      name: quagga
      state: latest
    tags:
      - packages

  - name: Configure guagga ABR1
    copy:
      src: "zebra_1.conf"
      dest: "/etc/quagga/zebra.conf"
  
  - name: Configure guagga ABR1
    copy:
      src: "ospfd_1.conf"
      dest: "/etc/quagga/ospfd.conf"
    when: ansible_hostname == 'ABR1'
    notify: restart quagga

  - name: Configure guagga ABR2
    copy:
      src: "{{ item }}"
      dest: "/etc/quagga/{{ item }}"
    loop:
      - zebra_2.conf
      - ospfd_2.conf
    when: ansible_hostname == 'ABR2'
    notify: restart quagga

  - name: Configure guagga ABR3
    copy:
      src: "{{ item }}"
      dest: "/etc/quagga/{{ item }}"
    loop:
      - zebra_3.conf
      - ospfd_3.conf
    when: ansible_hostname == 'ABR3'
    notify: restart quagga