---
  - name: install quagga
    yum:
      name: quagga
      state: latest
    tags:
      - packages
  
  - name: Configure guagga ABR1
    copy:
      src: "{{ item }}"
      dest: "/etc/quagga/{{ item }}"
      whith_item:
         - zebra_1.conf
         - osfpd_1.conf
      when: 
      nostname:
         - ABR1
    notify: restart quagga
  
  - name: Configure guagga ABR2
    copy:
      src: "{{ item }}"
      dest: "/etc/quagga/{{ item }}"
      whith_item:
         - zebra_2.conf
         - osfpd_2.conf
      when: 
      nostname:
         - ABR2
    notify: restart quagga
  
  - name: Configure guagga ABR3
    copy:
      src: "{{ item }}"
      dest: "/etc/quagga/{{ item }}"
      whith_item:
         - zebra_3.conf
         - osfpd_3.conf
      when: 
      nostname:
         - ABR3
    notify: restart quagga

