---
  - name: install quagga
    yum:
      name: quagga
      state: latest
    tags:
      - packages

  - name: Configure zebra ABR1
    copy:
      src: "zebra_1.conf"
      dest: "/etc/quagga/zebra.conf"
    when: ansible_hostname == 'ABR1'

  - name: Configure ospf ABR1
    copy:
      src: "ospfd_1.conf"
      dest: "/etc/quagga/ospfd.conf"
    when: ansible_hostname == 'ABR1'
    notify: restart quagga

  - name: Configure zebra ABR2
    copy:
      src: "zebra_2.conf"
      dest: "/etc/quagga/zebra.conf"
    when: ansible_hostname == 'ABR2'

  - name: Configure ospf ABR2
    copy:
      src: "ospfd_2.conf"
      dest: "/etc/quagga/ospfd.conf"
    when: ansible_hostname == 'ABR2'
    notify: restart quagga
  
  - name: Configure zebra ABR3
    copy:
      src: "zebra_3.conf"
      dest: "/etc/quagga/zebra.conf"
    when: ansible_hostname == 'ABR3'

  - name: Configure osfd ABR3
    copy:
      src: "ospfd_3.conf"
      dest: "/etc/quagga/ospfd.conf"
    when: ansible_hostname == 'ABR3'
    notify: restart quagga