---
- name: restart dovecot
  systemd:
    name: dovecot
    state: reloaded

- name: restart postfix
  systemd:
    name: postfix
    state: reloaded

- name: start mysql
  systemd:
     name: mysql
     state: started
