---
- name: restart dovecot
  systemd:
    name: dovecot
    state: restarted

- name: restart postfix
  systemd:
    name: postfix
    state: restarted

- name: restart mysql
  systemd:
     name: mysql
     state: restarted
