# tasks file nginx start 8080 port
---
  - name: install packeges
    yum:
     name: nginx
     state: latest
    tags: 
    - packages
    
  - name: update conf nginx
    template:
      src: /etc/ansible/nginx/temlates/nginx.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
    notify: restart nginx
