---
postfix_generic_maps: {}
postfix_packages: []
postfix_parameters:
  alias_database: 'hash:/etc/aliases'
  alias_maps: 'hash:/etc/aliases'
  command_directory: /usr/sbin
  daemon_directory: /usr/libexec/postfix
  data_directory: /var/lib/postfix
  debug_peer_level: 2
  debugger_command: 'PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin ddd $daemon_directory/$process_name $process_id & sleep 5'
  html_directory: false
  inet_interfaces: localhost
  inet_protocols: all
  mail_owner: postfix
  mailq_path: /usr/bin/mailq.postfix
  manpage_directory: /usr/share/man
  mydestination:
    - $myhostname
    - localhost.$mydomain
    - localhost
  newaliases_path: /usr/bin/newaliases.postfix
  readme_directory: "/usr/share/doc/postfix-{{ postfix_version }}/README_FILES"
  sample_directory: "/usr/share/doc/postfix-{{ postfix_version }}/samples"
  sendmail_path: /usr/sbin/sendmail.postfix
  setgid_group: postdrop
  queue_directory: /var/spool/postfix
  unknown_local_recipient_reject_code: 550

