---
- name: install haproxy
  yum: 
    name: haproxy 
    state: present

- name: Copy across new haproxy.conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - reload haproxy
