---
- name: Attempting to overlay postfix configurations
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  register: postfix_template
  notify: restart postfix

- name: Attempting to overlay postfix generic maps, if applicable
  template:
    src: generic.j2
    dest: /etc/postfix/generic
    owner: root
    group: root
    mode: 0600
  notify: postmap generic
  when:
    - postfix_generic_maps|length > 0
    - postfix_parameters.smtp_generic_maps is defined

- name: Attempting to overlay postfix sasl password maps, if applicable
  no_log: true
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  notify: postmap sasl_passwd
  when:
    - postfix_parameters.relayhost is defined
    - postfix_parameters.smtp_sasl_password_maps is defined
    - postfix_sasl_password is defined
    - postfix_sasl_username is defined

