# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  # config.vm.provision "ansible" do |ansible|
  #   ansible.verbose = "vvv"
  #   ansible.playbook = "provisioning/playbook.yml"
  #   ansible.become = "true"
  # end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    ns01.vm.hostname = "ns01"
    ns01.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
    yum install ansible -y
    cp -r /vagrant/* /etc/ansible
  SHELL
  end

  config.vm.define "ns02" do |ns02|
    ns02.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "dns"
    ns02.vm.hostname = "ns02"
    ns02.vm.provision "shell", inline: <<-SHELL
  mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
  sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl restart sshd
SHELL
end

  config.vm.define "client1" do |client1|
    client1.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
    client1.vm.hostname = "client1"
    client1.vm.provision "shell", inline: <<-SHELL
  mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
  sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl restart sshd
SHELL
end
  config.vm.define "client2" do |client2|
    client2.vm.network "private_network", ip: "192.168.50.16", virtualbox__intnet: "dns"
    client2.vm.hostname = "client2"
    client2.vm.provision "shell", inline: <<-SHELL
  mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
  sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl restart sshd
SHELL
end

end
