# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

config.vm.provider "virtualbox" do |v|
   v.memory = 256
end

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "inventory"
    ansible.playbook = "site.yml"
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.network "forwarded_port", guest: 80, host: 8080
    proxy.vm.network "private_network", ip: "192.168.50.2"
    proxy.vm.hostname = "proxy.internal"
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "private_network", ip: "192.168.50.4"
    mysql.vm.hostname = "mysql.internal"
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.50.5"
    web.vm.hostname = "web.internal"
  end

    config.vm.define "web2" do |web2|
    web2.vm.network "private_network", ip: "192.168.50.6"
    web2.vm.hostname = "web2.internal"
  end
  
  config.vm.define "web3" do |web3|
    web3.vm.network "private_network", ip: "192.168.50.7"
    web3.vm.hostname = "web3.internal"
  end

end

