# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  # config.vm.provision "ansible" do |ansible|
  #   ansible.verbose = "vvv"
  #   ansible.playbook = "mail.yml"
  #   ansible.become = "true"
  # end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.255.1", virtualbox__intnet: "iptab"
    master.vm.hostname = "master"
    master.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
    rpm -Uvh http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
    yum update -y
  SHELL
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.255.2", virtualbox__intnet: "iptab"
    slave.vm.hostname = "slave"
    slave.vm.provision "shell", inline: <<-SHELL
  mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
  sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl restart sshd
  rpm -Uvh http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
  yum update -y
  SHELL
end

config.vm.define "slave2" do |slave2|
  slave2.vm.network "private_network", ip: "192.168.255.3", virtualbox__intnet: "iptab"
  slave2.vm.hostname = "slave2"
  slave2.vm.provision "shell", inline: <<-SHELL
mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd
yum install ansible -y
rpm -Uvh http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
yum update -y
cp -a /vagrant/* /etc/ansible/
cd /etc/ansible
# ansible-playbook postgres.yml
SHELL
end

end