---
    - name: Install Packages
      include: packages.yml

    - name: Master Setup
      include: master.yml
      when: 
         "'pmasters' in group_names"

    - name: Setup Slaves when they are new slaves
      include: slave.yml
      when:
       - "'pslaves' in group_names"

