---
    - name: Check if Postgres is installed
      stat: path=/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      register: is_installed

    - name: Check if already a slave
      stat: path={{ data_directory }}/recovery.conf
      register: recovery

    - name: Install Packages
      include: packages.yml
      when: is_installed.stat.exists == False

    - name: Stop Slave Postgres service
      service: name=postgresql state=stopped
      when: 
        - "'pslaves' in group_names"
        - recovery.stat.exists == False

    - name: Master Setup
      include: master.yml
      when: "'pmasters' in group_names"

    - name: Setup Slaves when they are new slaves
      include: slave.yml
      when:
       - "'pslaves' in group_names"
       - recovery.stat.exists == False
