---
    # - name: Stop Postgresql
    #   systemd: 
    #     name: postgresql-9.5 
    #     state: stopped

    # - name: run initdb on directory
    #   raw: su postgres -c '/usr/pgsql-"{{ postgresql_version }}"/bin/initdb -E UTF8 -D /var/lib/pgsql/"{{ postgresql_version }}"/data'
    - name: initdb master
      remote_user: postgres
      command: /usr/pgsql-9.5/bin/postgresql95-setup initdb
    
    - name: start postgres
      command: systemctl start postgresql-9.5

    - name: Create {{db_name}} database
      postgresql_db:
        name: test 
        encoding: UTF-8
        template: template0

    - name: Create rep user
      postgresql_user:
        db: test
        name: rep
        password: rep_password
        role_attr_flags: Replication
        priv: "CONNECT/products:ALL"
        expires: infinity

    - name: create pg_hba.conf
      template:
        src: pg_hba.conf.j2
        dest: /var/lib/pgsql/9.5/data/pg_hba.conf
           
    - name: create postgresql.conf
      template:
        src: postgresql.conf.j2
        dest: /var/lib/pgsql/9.5/data/postgresql.conf
    
    - name: start Postgresql service
      systemd: 
        enabled: yes
        name: postgresql-9.5 
        state: started
    

    

 
    # - name: Drop Replication user if exists
    #   raw: su - postgres -c 'psql -c "drop user if exists {{ rep_user }};"'
    
  

    # - name: Create a Rep User
    #   raw: su - postgres -c 'psql -c "CREATE USER {{ rep_user }} REPLICATION LOGIN CONNECTION LIMIT 5 ENCRYPTED PASSWORD '{{ rep_password }}';"'

    # - name: Add postgres config directives
    #   lineinfile: 
    #     path: /var/lib/pgsql/9.5/data/postgresql.conf 
    #     line: "{{ item }}"
    #   loop:
    #     - "{{ postgres_vars }}"

   
