---
    - name: install postgres packages
      yum:
         name: "{{ item }}"
      loop:
        - "{{ system_packages }}"
      sudo: yes

    # - name: change data directory
    #   include: data_dir.yml
