---
    # - name: stop postgresql-9.5
    #   systemd:
    #     name: postgresql-9.5
    #     state: stopped
    
    - name: initdb slave
      remote_user: postgres
      command: /usr/pgsql-9.5/bin/postgresql95-setup initdb
    
    - name: create slave pg_hba.conf
      template:
        src: pg_hba.conf.j2
        dest: /var/lib/pgsql/9.5/data/pg_hba.conf 
    
    - name: create slave pg_hba.conf
      template:
        src: pg_hba.conf.j2
        dest: /var/lib/pgsql/9.5/data/pg_hba.conf

    # - name: Base Backup
    #   command: su - postgres -c "pg_basebackup -h 192.168.255.1 -D /var/lib/pgsql/"{{ postgresql_version }}"/data -R -P -U replication --xlog-method=stream"
    #   environment:
    #     PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    #   loop:
    #     - "{{ groups['pmasters'] }}"

    - name: create recovery.conf
      template:
        src: recovery.conf.j2
        dest: /var/lib/pgsql/9.5/data/recovery.conf

    - name: Start Slave Postgres Service
      systemd: 
         name: postgresql-9.5
         enabled: yes 
         state: started
