---

<<<<<<< HEAD
=======
- name: Configure LDAP lookups for sudo (1/2)
  lineinfile: "dest=/etc/nsswitch.conf regexp='sudoers:    files    ldap' insertafter=EOF  line='sudoers:    files    ldap'"

- name: Configure LDAP lookups for sudo (2/2)
  lineinfile: "dest=/etc/rc.d/rc.local regexp='nisdomainname {{ domain_search }}' insertafter=EOF  line='nisdomainname {{ domain_search }}'"


>>>>>>> ae6050ab3c81816de1aaaa643072a0220e8d31a7
- name: Configure LDAP binding for the sudo lookup
  lineinfile: "dest=/etc/sudo-ldap.conf regexp='{{ item }}' insertafter=EOF line='{{ item }}'"
  with_items:
    - binddn
    - uid=sudo,cn=sysaccounts,cn=etc,dc={{ dc1 }},dc={{ dc0 }}
    - bindpw {{ password }} 
    - ssl start_tls
    - tls_cacertfile {{ tls_cacertfile_path }}
    - tls_checkpeer yes
    - uri {{ uri_LDAP }}
    - sudoers_base ou=SUDOers,dc={{ dc1 }},dc={{ dc0 }}
    - bind_timelimit 5
    - timelimit 10
