---

- name: Create the vlan iface
  template: src=el_ifcfg-vlans.j2 dest="{{ el_network_sysconfig }}/ifcfg-{{ item.name }}"
  with_items:
  - "{{ vlans }}"
  when:
  - apply
  - ("{{ slaves| length }}" >=2)
  - v1.vlan
  notify: restart network
  tags:
  - el
  - bond

- name: Apply settings NOW
  service: name=network state=restarted
  when:
  - apply_now


- name: Create the vlan iface
  template: src=el_ifcfg-vlans.j2 dest="{{ tmp_dir }}/ifcfg-{{ item.name }}"
  with_items:
  - "{{ vlans }}"
  when:
  - not apply
  - ("{{ slaves| length }}" >=2)
  - v1.vlan
  tags:
  - el
  - bond
